### ISSUE TITLE
request feedback on topics for UCLA spring quarter 2020 R class

### ISSUE THREAD

**Issue by ozanj** [eddatasci/unrollment_proj#12]
Hi all,

In order for me - and I think Patricia too - to allocate substantial time to the unrollment_proj, I want to maximize synergy between work on unrollment_proj and my spring quarter 2020 R class, which I will co-develop with Patricia in Winter 2020 and Patricia will be TA.

Question for you all: I would like you to comment on the list of topics I will cover

I will assume that students know the topics from the first 10 "modules" of my/Karina's fall 2020 [R-class](https://ozanj.github.io/rclass/resources/)

I only have 10 weeks and my approach is to cover fewer topics, at slower pace, in more depth and students complete problem sets each week to practice concepts.

to the extent possible, I'll try to use datasets we are using for unrollment_proj. Also, this curriculum we develop could be part of a grant proposal that promises to provide tutorials/free online courses on the R skills we are using in unrollment_proj

Here is my tentative list of topics by week number [and I don't know how to do most of these things yet!]

1. introduction to visualization/graphing w/ ggplot
2. introduction to github [for rest of quarter students will be required to use github for problem sets, etc]; potentially might introduce general info on using APIs in R

3-WEEK UNIT ON STRINGS/REGULAR EXPRESSIONS [want to spend three weeks on this cuz regular expressions are hard]
3. strings/regular expressions 1
4. strings/regular expressions 2 [potential application: twitter data and/or web-scraping followed by pasing]
5. strings/regular expressions 3  [potential application: twitter data and/or web-scraping followed by pasing]

3-WEEK UNIT ON PROGRAMMING
6. iteration [basic, not purr]
7. writing functions
8. selected additional core programming skills. For example, programming skills for writing functions that work with tidyverse (e.g., quosure, evaluation, lazy vs. tidy evaluation)

WEEKS 9 AND 10

- not sure what to do w/ weeks 9 and 10. so this is where I would particularly appreciate your advice
- my instinct from previous teaching experience is to choose one topic and spend two weeks on it to give students some depth and practice, as opposed to bombarding them with two complicated topics.
- my sense is that students would be most excited with an introduction to mapping/gis type stuff. but not sure if that can be done well enough in two weeks. also, not sure if this is a sufficiently "core" skill or if this is just an application and I should instead choose something that is more "core." also, if unrollment_proj includes some mapping then a two-week unit on mapping becomes more attractive
- alternative topics could include: machine learning [will our algorithms for unrollment_proj utilize machine learning?]; network analysis; I don't know anything about APIs in R, so maybe it would it be good to spend a week earlier in course on APIs

all thoughts/criticisms/musings welcome!

**Comment by wdoyle42** [comment]
Not to be harsh, but marking this as off-topic and closing. Would be (truly) happy to discuss this in another forum.
