### ISSUE TITLE
R function to create restructured data for cross validation

### ISSUE THREAD

**Issue by wdoyle42** [eddatasci/unrollment_proj#16]
R function that will take data that was read in from ELS and cleaned and will structure it for resampling. 

Inputs: data set, type of resampling (k-fold, bootstrap) and resampling options (number of folds, number of replicates)

Outputs: dataset structured for resampling

**Comment by btskinner** [comment]
**To Do**

- [ ] add [testthat](https://testthat.r-lib.org) unit tests to check various resampling methods

**Comment by btskinner** [comment]
Adding more tests for utility functions and setting up Travis-CI per #11. When it runs, I will probably just merge unless @wdoyle42, you have an issue with my doing that.

**Comment by wdoyle42** [comment]
Resolved via 1af418d6df60bcd331840ff32d9998ac77238e0e
