### ISSUE TITLE
E-net classification model

### ISSUE THREAD

**Issue by wdoyle42** [eddatasci/unrollment_proj#18]
Function that will generate predicted probabilities from the restructured data using an elastic net logistic regression model.

**Comment by wdoyle42** [comment]
Hard to see why to do this, given that it's now just 

```{r}
grad_mod<-
  logistic_reg(penalty=tune(),mixture = tune())%>%
  set_engine("glmnet")
```

via workflows, per #23 

I have now shown flexibility by asking and answering my own question.

**Comment by btskinner** [comment]
@wdoyle42, [rubber duck debugging](https://rubberduckdebugging.com) at its finest.
