### ISSUE TITLE
Change "master" branch to "main"

### ISSUE THREAD

**Issue by btskinner** [eddatasci/unrollment_proj#30]
I propose that we change the name of the default branch, which is currently **master** to **main**. [I believe that GitHub is making this change](https://twitter.com/natfriedman/status/1271253144442253312), but it's unclear when it will happen and whether it will be retroactive for existing repositories (I would assume not). I have started this process with my repos and am happy to take the lead here. 

Can others vote, either by commenting below or giving a thumbs up? If we decide to make the change, I'll have a few small steps for everyone to complete before I do. 

Thanks, everyone.

**Comment by mositelu** [comment]
Sounds good to me.

**Comment by wdoyle42** [comment]
Sounds good to me as well.

**Comment by btskinner** [comment]
Completed. To get the new branch and delete the local old version of `master`:

```bash
## inside the unrollment_proj directory on your machine
git pull
git checkout main
git branch -d master
```
